# Generated by Django 4.1.3 on 2022-11-03 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="photo",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="faulty_report"),
        ),
        migrations.AlterField(
            model_name="report",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("user_type", "technician")),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
