# Generated by Django 4.1.3 on 2022-11-13 15:20

from django.db import migrations, models
import facility_mgn.utils


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0002_historicalreport_photo_report_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "tracking_number",
                    models.CharField(
                        default=facility_mgn.utils.genserial, max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/facility/inventory"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Facility Inventory",
                "verbose_name_plural": "Facilities Inventory",
                "ordering": ("-updated",),
            },
        ),
    ]
