# Generated by Django 4.1.3 on 2022-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("technician", "Technician"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                max_length=255,
            ),
        ),
    ]
