# Generated by Django 4.1.3 on 2022-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="zip_code",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("technician", "Technician"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="student",
                max_length=255,
            ),
        ),
    ]
