NIGERIA_STATES = (
    ("ABIA", "ABIA"),
    ("ABUJA", "ABUJA"),
    ("ADAMAWA", "ADAMAWA"),
    ("AKWA IBOM", "AKWA IBOM"),
    ("ANAMBRA", "ANAMBRA"),
    ("BAUCHI", "BAUCHI"),
    ("BAYELSA", "BAYELSA"),
    ("BENUE", "BENUE"),
    ("BORNO", "BORNO"),
    ("CROSS RIVER", "CROSS RIVER"),
    ("DELTA", "DELTA"),
    ("EBONYI", "EBONYI"),
    ("EDO", "EDO"),
    ("EKITI", "EKITI"),
    ("ENUGU", "ENUGU"),
    ("GOMBE", "GOMBE"),
    ("IMO", "IMO"),
    ("JIGAWA", "JIGAWA"),
    ("KADUNA", "KADUNA"),
    ("KANO", "KANO"),
    ("KATSINA", "KATSINA"),
    ("KEBBI", "KEBBI"),
    ("KOGI", "KOGI"),
    ("KWARA", "KWARA"),
    ("LAGOS", "LAGOS"),
    ("NASSARAWA", "NASSARAWA"),
    ("NIGER", "NIGER"),
    ("OGUN", "OGUN"),
    ("ONDO", "ONDO"),
    ("OSUN", "OSUN"),
    ("OYO", "OYO"),
    ("PLATEAU", "PLATEAU"),
    ("RIVERS", "RIVERS"),
    ("SOKOTO", "SOKOTO"),
    ("TARABA", "TARABA"),
    ("YOBE", "YOBE"),
    ("ZAMFARA", "ZAMFARA"),
    ("NON NIGERIAN", "NON NIGERIAN"),
)

STATES_LIST = [
    "ABIA",
    "ABUJA",
    "ADAMAWA",
    "AKWA IBOM",
    "ANAMBRA",
    "BAUCHI",
    "BAYELSA",
    "BENUE",
    "BORNO",
    "CROSS RIVER",
    "DELTA",
    "EBONYI",
    "EDO",
    "EKITI",
    "ENUGU",
    "GOMBE",
    "IMO",
    "JIGAWA",
    "KADUNA",
    "KANO",
    "KATSINA",
    "KEBBI",
    "KOGI",
    "KWARA",
    "LAGOS",
    "NASSARAWA",
    "NIGER",
    "OGUN",
    "ONDO",
    "OSUN",
    "OYO",
    "PLATEAU",
    "RIVERS",
    "SOKOTO",
    "TARABA",
    "YOBE",
    "ZAMFARA",
    "NON NIGERIAN",
]
